redo.utils.cmd(["gcc", "-c", "-o", basename + ".o", basename + ".c"])
deps_string = redo.utils.cmd_output(["gcc", "-M", basename + ".c"])
deps = redo.utils.parse_makefile_dependency(deps_string)
deps.append (basename+".c")
redo.if_changed(*deps )
